#!/usr/bin/env bash
set -euo pipefail

export APP_BIND_HOST="${APP_BIND_HOST:-0.0.0.0}"
export APP_RUNTIME_DIR="${APP_RUNTIME_DIR:-.runtime}"
export GRAPH_DB_PATH="${GRAPH_DB_PATH:-${APP_RUNTIME_DIR}/knowledge_graph.db}"
export KGTS_VECTOR_INDEX_DIR="${KGTS_VECTOR_INDEX_DIR:-${APP_RUNTIME_DIR}/vector_index}"
export APP_BOOTSTRAP_SEED_DATA="${APP_BOOTSTRAP_SEED_DATA:-1}"
export APP_RUN_STARTUP_MAINTENANCE="${APP_RUN_STARTUP_MAINTENANCE:-0}"
export RENDER_AUTO_SYNC_STRUCTURED="${RENDER_AUTO_SYNC_STRUCTURED:-0}"
export DEEPSEEK_GENERATION_READ_TIMEOUT_SECONDS="${DEEPSEEK_GENERATION_READ_TIMEOUT_SECONDS:-0}"

# Azure/low-memory default: keep features enabled, but do not keep heavyweight
# models resident in the main web process.
export KGTS_RETRIEVAL_MODE="${KGTS_RETRIEVAL_MODE:-hybrid}"
export KGTS_VECTOR_STARTUP_ENSURE="${KGTS_VECTOR_STARTUP_ENSURE:-0}"
export KGTS_VECTOR_UNLOAD_AFTER_QUERY="${KGTS_VECTOR_UNLOAD_AFTER_QUERY:-1}"
export KGTS_VECTOR_UNLOAD_AFTER_REBUILD="${KGTS_VECTOR_UNLOAD_AFTER_REBUILD:-1}"
export KGTS_VECTOR_HASH_FALLBACK="${KGTS_VECTOR_HASH_FALLBACK:-1}"
export KGTS_TTS_ENABLED="${KGTS_TTS_ENABLED:-1}"
export KGTS_TTS_PROVIDER="${KGTS_TTS_PROVIDER:-genie_server}"
export KGTS_TTS_SERVER_URL="${KGTS_TTS_SERVER_URL:-http://127.0.0.1:9880}"

PORT="${PORT:-8000}"

exec python -m uvicorn render_app:app --host 0.0.0.0 --port "$PORT"
