#!/usr/bin/env bash
set -euo pipefail

export APP_BIND_HOST="${APP_BIND_HOST:-0.0.0.0}"
export APP_BOOTSTRAP_SEED_DATA="${APP_BOOTSTRAP_SEED_DATA:-1}"
export APP_RUN_STARTUP_MAINTENANCE="${APP_RUN_STARTUP_MAINTENANCE:-0}"
export RENDER_AUTO_SYNC_STRUCTURED="${RENDER_AUTO_SYNC_STRUCTURED:-0}"
export DEEPSEEK_GENERATION_READ_TIMEOUT_SECONDS="${DEEPSEEK_GENERATION_READ_TIMEOUT_SECONDS:-0}"

PORT="${PORT:-8000}"

exec python -m uvicorn render_app:app --host 0.0.0.0 --port "$PORT"
