/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as TeacherPrepareRouteImport } from './routes/teacher/prepare'
import { Route as TeacherPptRouteImport } from './routes/teacher/ppt'
import { Route as TeacherLectureRouteImport } from './routes/teacher/lecture'
import { Route as TeacherExercisesRouteImport } from './routes/teacher/exercises'
import { Route as StudentReviewRouteImport } from './routes/student/review'
import { Route as StudentPracticeRouteImport } from './routes/student/practice'
import { Route as StudentLearnRouteImport } from './routes/student/learn'
import { Route as GraphAdminRouteImport } from './routes/graph/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPrepareRoute = TeacherPrepareRouteImport.update({
  id: '/teacher/prepare',
  path: '/teacher/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPptRoute = TeacherPptRouteImport.update({
  id: '/teacher/ppt',
  path: '/teacher/ppt',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLectureRoute = TeacherLectureRouteImport.update({
  id: '/teacher/lecture',
  path: '/teacher/lecture',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExercisesRoute = TeacherExercisesRouteImport.update({
  id: '/teacher/exercises',
  path: '/teacher/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReviewRoute = StudentReviewRouteImport.update({
  id: '/student/review',
  path: '/student/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/student/practice',
  path: '/student/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLearnRoute = StudentLearnRouteImport.update({
  id: '/student/learn',
  path: '/student/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphAdminRoute = GraphAdminRouteImport.update({
  id: '/graph/admin',
  path: '/graph/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/graph/admin': typeof GraphAdminRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/review': typeof StudentReviewRoute
  '/teacher/exercises': typeof TeacherExercisesRoute
  '/teacher/lecture': typeof TeacherLectureRoute
  '/teacher/ppt': typeof TeacherPptRoute
  '/teacher/prepare': typeof TeacherPrepareRoute
  '/graph/': typeof GraphIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/graph/admin': typeof GraphAdminRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/review': typeof StudentReviewRoute
  '/teacher/exercises': typeof TeacherExercisesRoute
  '/teacher/lecture': typeof TeacherLectureRoute
  '/teacher/ppt': typeof TeacherPptRoute
  '/teacher/prepare': typeof TeacherPrepareRoute
  '/graph': typeof GraphIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/graph/admin': typeof GraphAdminRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/review': typeof StudentReviewRoute
  '/teacher/exercises': typeof TeacherExercisesRoute
  '/teacher/lecture': typeof TeacherLectureRoute
  '/teacher/ppt': typeof TeacherPptRoute
  '/teacher/prepare': typeof TeacherPrepareRoute
  '/graph/': typeof GraphIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/graph/admin'
    | '/student/learn'
    | '/student/practice'
    | '/student/review'
    | '/teacher/exercises'
    | '/teacher/lecture'
    | '/teacher/ppt'
    | '/teacher/prepare'
    | '/graph/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/graph/admin'
    | '/student/learn'
    | '/student/practice'
    | '/student/review'
    | '/teacher/exercises'
    | '/teacher/lecture'
    | '/teacher/ppt'
    | '/teacher/prepare'
    | '/graph'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/graph/admin'
    | '/student/learn'
    | '/student/practice'
    | '/student/review'
    | '/teacher/exercises'
    | '/teacher/lecture'
    | '/teacher/ppt'
    | '/teacher/prepare'
    | '/graph/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  GraphAdminRoute: typeof GraphAdminRoute
  StudentLearnRoute: typeof StudentLearnRoute
  StudentPracticeRoute: typeof StudentPracticeRoute
  StudentReviewRoute: typeof StudentReviewRoute
  TeacherExercisesRoute: typeof TeacherExercisesRoute
  TeacherLectureRoute: typeof TeacherLectureRoute
  TeacherPptRoute: typeof TeacherPptRoute
  TeacherPrepareRoute: typeof TeacherPrepareRoute
  GraphIndexRoute: typeof GraphIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/prepare': {
      id: '/teacher/prepare'
      path: '/teacher/prepare'
      fullPath: '/teacher/prepare'
      preLoaderRoute: typeof TeacherPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/ppt': {
      id: '/teacher/ppt'
      path: '/teacher/ppt'
      fullPath: '/teacher/ppt'
      preLoaderRoute: typeof TeacherPptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/lecture': {
      id: '/teacher/lecture'
      path: '/teacher/lecture'
      fullPath: '/teacher/lecture'
      preLoaderRoute: typeof TeacherLectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/exercises': {
      id: '/teacher/exercises'
      path: '/teacher/exercises'
      fullPath: '/teacher/exercises'
      preLoaderRoute: typeof TeacherExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/review': {
      id: '/student/review'
      path: '/student/review'
      fullPath: '/student/review'
      preLoaderRoute: typeof StudentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/student/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/learn': {
      id: '/student/learn'
      path: '/student/learn'
      fullPath: '/student/learn'
      preLoaderRoute: typeof StudentLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/admin': {
      id: '/graph/admin'
      path: '/graph/admin'
      fullPath: '/graph/admin'
      preLoaderRoute: typeof GraphAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  GraphAdminRoute: GraphAdminRoute,
  StudentLearnRoute: StudentLearnRoute,
  StudentPracticeRoute: StudentPracticeRoute,
  StudentReviewRoute: StudentReviewRoute,
  TeacherExercisesRoute: TeacherExercisesRoute,
  TeacherLectureRoute: TeacherLectureRoute,
  TeacherPptRoute: TeacherPptRoute,
  TeacherPrepareRoute: TeacherPrepareRoute,
  GraphIndexRoute: GraphIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
