"""Exercise helpers - re-export from modular submodules.

This module re-exports the public API for backward compatibility.
New code should import directly from the submodules:
  - KGTS.education.exercise_text_utils
  - KGTS.education.exercise_formula_utils
  - KGTS.education.exercise_quality
  - KGTS.education.exercise_bank
  - KGTS.education.exercise_generation
"""
from __future__ import annotations

from KGTS.education.exercise_bank import (
    _attach_exercise_feedback,
    _build_exercise_feedback_guidance,
    _exercise_feedback_for_item,
    _exercise_feedback_map,
    _exercise_feedback_summary,
    _exercise_option_feedback_key,
    _exercise_signature,
    _extract_json_object_text,
    _filter_downvoted_exercises,
    _merge_all_exercise_banks,
    _normalize_exercise_bank,
    _normalize_correct_answer,
    _option_compare_key,
    _remove_exercise_from_bank,
    _replace_exercise_in_bank,
    _replace_option_in_exercise,
    _same_exercise_target,
    _same_question_option_history,
)
from KGTS.education.exercise_formula_utils import (
    _correct_option_length_outlier,
    _extract_formula_candidates,
    _formula_distractors,
    _is_pure_formula_text,
    _looks_like_short_math_part,
    _latex_option_text,
    _looks_like_formula_text,
    _option_length_score,
    _split_latex_fraction,
)
from KGTS.education.exercise_generation import (
    _build_local_exercise_bank,
    _build_local_exercise_response,
    _find_exercise_for_feedback,
    _generate_replacement_option_text,
    _get_exercise_evidence,
    _local_replacement_option,
)
from KGTS.education.exercise_quality import (
    _has_reused_option_set,
    _is_bad_exercise_question,
    _is_low_quality_exercise,
    _is_placeholder_exercise,
    _merge_exercise_banks,
)
from KGTS.education.exercise_text_utils import (
    TEACHING_SCAFFOLD_MARKERS,
    GENERIC_FACT_LABELS,
    _clean_exercise_text,
    _compact_learning_text,
    _compact_question_text,
    _contains_latex_math,
    _format_options,
    _is_generic_fact_label,
    _is_mostly_english,
    _is_teaching_scaffold_text,
    _normalize_exercise_options,
    _normalize_math_text,
    _strip_english_discourse_prefix,
    _strip_markdown_label,
    _strip_option_letter,
    _strip_reference_markers,
    _target_exercise_count,
)

__all__ = [
    "TEACHING_SCAFFOLD_MARKERS",
    "GENERIC_FACT_LABELS",
    "_normalize_exercise_options",
    "_normalize_correct_answer",
    "_target_exercise_count",
    "_is_placeholder_exercise",
    "_strip_reference_markers",
    "_contains_latex_math",
    "_normalize_math_text",
    "_clean_exercise_text",
    "_is_mostly_english",
    "_strip_option_letter",
    "_strip_english_discourse_prefix",
    "_strip_markdown_label",
    "_is_teaching_scaffold_text",
    "_is_generic_fact_label",
    "_compact_learning_text",
    "_compact_question_text",
    "_format_options",
    "_option_length_score",
    "_correct_option_length_outlier",
    "_looks_like_formula_text",
    "_is_pure_formula_text",
    "_extract_formula_candidates",
    "_formula_distractors",
    "_split_latex_fraction",
    "_latex_option_text",
    "_looks_like_short_math_part",
    "_is_bad_exercise_question",
    "_is_low_quality_exercise",
    "_merge_exercise_banks",
    "_exercise_option_token_set",
    "_has_reused_option_set",
    "_normalize_exercise_bank",
    "_exercise_signature",
    "_exercise_feedback_map",
    "_exercise_feedback_for_item",
    "_exercise_option_feedback_key",
    "_attach_exercise_feedback",
    "_filter_downvoted_exercises",
    "_same_exercise_target",
    "_remove_exercise_from_bank",
    "_merge_all_exercise_banks",
    "_exercise_feedback_summary",
    "_build_exercise_feedback_guidance",
    "_extract_json_object_text",
    "_replace_option_in_exercise",
    "_replace_exercise_in_bank",
    "_option_compare_key",
    "_same_question_option_history",
    "_local_replacement_option",
    "_find_exercise_for_feedback",
    "_get_exercise_evidence",
    "_build_local_exercise_bank",
    "_build_local_exercise_response",
    "_generate_replacement_option_text",
]
